spring.application.name=be
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mainprofit10@gmail.com
spring.mail.password=dioe thgk oqts rcvq

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

stripe.secret.key=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