spring.application.name=be
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mainprofit10@gmail.com
spring.mail.password=dioe thgk oqts rcvq

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Fallback key pentru build pe Railway
stripe.secret.key=${STRIPE_SECRET_KEY:sk_test_dummy_for_tests}

# Port Railway
server.port=${PORT:8080}